services:
  postgres:
    image: 'postgres:18'
    container_name: aji_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aji_db
    ports:
      - "6767:5432"
    volumes:
      - aji_postgres_data:/var/lib/postgresql
    networks:
      - aji-network